x = int('123')
a = float('123.42')
b = complex('3+4j')
c = str(12)
d = bool('True')
e = bin(25) #binary
f = oct(25)
g = hex(25)
h = ord('A') #char to unicode
i = chr(100) #unicode to character
print(x,a,b,c,d,e,f,g,h,i,sep="\n")
